import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title className="text-2xl text-blue-500">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Event Dashboard &rarr;</h2>
            <p>View all events</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Create event &rarr;</h2>
            <p>Add events</p>
          </a>
        </div>
      </main>
    </div> 
  )
}
